name: newland
description: This app new app in gita homeworks


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  floor: ^1.4.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.1
  build_runner: ^2.1.2



flutter:


  uses-material-design: true
  assets:
    - asset/images/
